spring:
  datasource:
    url: ${DB_JDBC_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: true
  coolsms:
    apiKey: ${COOLSMS_KEY}
    apiSecret: ${COOLSMS_SECRET_KEY}
    senderNumber: ${COOLSMS_SENDER_NUMBER}
  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_SERVER}
      repositories:
        enable: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB

jwt:
  secret: ${JWT_SECRET}
  access-token-validity-in-milliseconds: ${ACCESS_TOKEN_VALIDITY_IN_MILLISECONDS}
  refresh-token-validity-in-milliseconds: ${REFRESH_TOKEN_VALIDITY_IN_MILLISECONDS}

fcm:
  api_url: ${FCM_API_URL}
  fcm_config: ${FCM_CONFIG}

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    credentials:
      accessKey: ${S3_KEY}
      secretKey: ${S3_SECRET_KEY}